name: tests

on: [push]

jobs:
  test:
    name: nargo test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.4
        with:
          toolchain: 1.0.0-beta.9

      - name: Run unit tests
        run: nargo test

      - name: Run integration tests
        run: |
          nargo execute --package depth_8_state_proof
          nargo execute --package depth_8_storage_proof
          nargo execute --package one_level
          nargo execute --package rlp_decode
