name: tests

on: [push]

jobs:
  test:
    name: nargo test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nargo
        uses: noir-lang/noirup@v0.1.4
        with:
          toolchain: 1.0.0-beta.9

      - name: Run nargo test
        run: nargo test
